### ISSUE TITLE
Monorepo w/ canonical LLVM hierarchy?

### ISSUE THREAD

**Issue by flowerhack** [llvm-project/llvm-project-20170507#1]
Hi hello!  Thank you for hosting this monorepo, it's very helpful!

I was wondering if it would make sense to organize the monorepo layout so that it matches the "canonical" layout for LLVM.  For instance: usually clang is checked out into the llvm tree, such that clang is located at llvm/tools/clang.  When you use the monorepo, however, llvm and clang are located at the same level of the tree.

Another example: usually compiler-rt is located in llvm/projects, but here it's located at the same level as llvm itself.

Such a layout would make it easier for instructions like these http://clang.llvm.org/get_started.html to work "out of the box", without having to pass a bunch of flags to point at the locations of different subparts of the project.

Would you consider rearranging the project this way?

Thank you for your time.

**Comment by chapuni** [comment]
I dislike legacy layout. Use;
- LLVM_EXTERNAL_*_SOURCE_DIR
- LLVM_ENABLE_PROJECTS

As a technical reason, Git's "tree" object is as same as each subproject. I am using git-plumbing, and not using git-filter-branch.

Thank you.

**Comment by andrewrk** [comment]
@flowerhack I exclusively build and install everything separately instead of using the legacy layout. This matches how it works in package managers such as Debian.
