### ISSUE TITLE
Monorepo destroyed?

### ISSUE THREAD

**Issue by AndrewPaxie** [llvm-project/llvm-project-20170507#2]
Did this commit just destroy the monorepo?

https://github.com/llvm-project/llvm-project-20170507/commit/91e0b1124ed5116bfc5ff4906ac2b6d563b35fd4

Only three files left in `llvm/lib/Target` when once there were 28,208 (approx) in `llvm`.

**Comment by octoploid** [comment]
And all because of the stupid #include removal to make the build 0.01% faster...

**Comment by chapuni** [comment]
Fixed. Thanks to let me know.
I don't know what happened. It's the first time such a breakage.

I think r320633 would not be the culprit. Just something went wrong.

**Comment by AndrewPaxie** [comment]
Thank you.  Can pull now, my nightly build is now in progress.

**Comment by chapuni** [comment]
@AndrewPaxie I heard the upstream llvm.org/llvm.git was broken for a short time. The breakage was due to it. Sorry for the inconvenience and thanks again to let me know.
