### ISSUE TITLE
Can't build LLVM Trunk for libc++ using Clang

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [llvm-project/llvm-project-20170507#3]
Hi, I'm aware this is not entirely an official LLVM distribution, and on that basis, my apologies for asking the question here.  (The LLVM project does not have a forum where I can ask my question.)

**Important** I just realised that I needed to use the `LIBCXX_BUILD_32_BITS=ON` switch to build for my 32bit platform (I had assumed the build would compile for the architecture I'm using, since I'm not cross-compiling.)  Having turned on the switch, I'm getting a CMake error: `LIBCXX_BUILD_32_BITS=ON is not supported on this platform.`
-=-=-=-

When I attempt to configure LLVM using `cmake -G "Unix Makefiles" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/lonelyfolder/usr ../llvm_src`
I get the following response with an error message stating that libstdc++ v4.8+ cannot be found (*Details about my GCC 4.8.5 are given at the bottom.*):  

    -- The C compiler identification is Clang 5.0.1
    -- The CXX compiler identification is Clang 5.0.1
    -- The ASM compiler identification is Clang
    -- Found assembler: /usr/local/bin/clang
    -- Check for working C compiler: /usr/local/bin/clang
    -- Check for working C compiler: /usr/local/bin/clang -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/local/bin/clang++
    -- Check for working CXX compiler: /usr/local/bin/clang++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- No build type selected, default to Debug
    -- Performing Test LLVM_NO_OLD_LIBSTDCXX
    -- Performing Test LLVM_NO_OLD_LIBSTDCXX - Failed
    CMake Error at cmake/modules/CheckCompilerVersion.cmake:38 (message):
      Host Clang must be able to find libstdc++4.8 or newer!
    Call Stack (most recent call first):
      cmake/config-ix.cmake:15 (include)
      CMakeLists.txt:578 (include)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/root/Downloads/LLVM/build.llvm/CMakeFiles/CMakeOutput.log".
    See also "/root/Downloads/LLVM/build.llvm/CMakeFiles/CMakeError.log".

I have been searching everywhere to get an explanation of why this is happening and how to overcome it but I am stuck.

If I use the `-DLLVM_ENABLE_LIBCXX=ON` option, I get past this problem because the `Performing Test LLVM_NO_OLD_LIBSTDCXX` test is skipped and I get a chance to use `make cxx`.  This option make me a little uncomfortable as I don't yet have libc++ installed (i.e. it is the reason I'm trying to build LLVM).  The last four lines of the cmake output (*I can post the entire cmake output if requested*) are:

    -- libc++ configuration differs from the abilist configuration. check-cxx-abilist target is not supported
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /root/Downloads/LLVM/build.llvm

When executing `make cxx` the build succeeds, but the tests, `make check-cxx check-cxxabi`, fail. Maybe that is what the message `check-cxx-abilist target is not supported` is trying to tell me.  Here is the output up to the 2nd test:

    [100%] Running libcxx tests
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/test/lit.cfg:45: note: Using configuration variant: libcxx
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/utils/libcxx/test/config.py:307: note: inferred use_system_cxx_lib as: None
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/utils/libcxx/test/config.py:313: note: inferred with_availability as: False
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/utils/libcxx/test/config.py:345: note: inferred use_clang_verify as: True
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/utils/libcxx/test/config.py:355: note: enabling thread-safety annotations
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/utils/libcxx/test/config.py:535: note: inferred language dialect as: c++2a
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/utils/libcxx/test/target_info.py:68: warning: The locale en_US.UTF-8 is not supported by your platform. Some tests will be unsupported.
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/utils/libcxx/test/target_info.py:68: warning: The locale fr_FR.UTF-8 is not supported by your platform. Some tests will be unsupported.
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/utils/libcxx/test/target_info.py:68: warning: The locale ru_RU.UTF-8 is not supported by your platform. Some tests will be unsupported.
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/utils/libcxx/test/target_info.py:68: warning: The locale zh_CN.UTF-8 is not supported by your platform. Some tests will be unsupported.
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/utils/libcxx/test/target_info.py:68: warning: The locale fr_CA.ISO8859-1 is not supported by your platform. Some tests will be unsupported.
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/utils/libcxx/test/target_info.py:68: warning: The locale cs_CZ.ISO8859-2 is not supported by your platform. Some tests will be unsupported.
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/utils/libcxx/test/config.py:436: note: inferred long_tests as: True
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/utils/libcxx/test/config.py:156: note: Using compiler: /usr/local/bin/clang++
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/utils/libcxx/test/config.py:157: note: Using flags: ['-v', '-D_LIBCPP_DISABLE_AVAILABILITY', '-ftemplate-depth=270']
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/utils/libcxx/test/config.py:162: note: Using compile flags: ['-Werror=thread-safety', '-std=c++2a', '-include', '/root/Downloads/LLVM/llvm_src/projects/libcxx/test/support/nasty_macros.hpp', '-nostdinc++', '-I/root/Downloads/LLVM/llvm_src/projects/libcxx/include', '-I/root/Downloads/LLVM/build.llvm/projects/libcxx/include/c++build', '-D__STDC_FORMAT_MACROS', '-D__STDC_LIMIT_MACROS', '-D__STDC_CONSTANT_MACROS', '-I/root/Downloads/LLVM/llvm_src/projects/libcxx/test/support', '-DLIBCXX_FILESYSTEM_STATIC_TEST_ROOT="/home/nao/Downloads/LLVM/llvm_src/projects/libcxx/test/std/experimental/filesystem/Inputs/static_test_env"', '-DLIBCXX_FILESYSTEM_DYNAMIC_TEST_ROOT="/home/nao/Downloads/LLVM/build.llvm/projects/libcxx/test/filesystem/Output/dynamic_env"', '-DLIBCXX_FILESYSTEM_DYNAMIC_TEST_HELPER="/usr/bin/python2.7 /root/Downloads/LLVM/llvm_src/projects/libcxx/test/support/filesystem_dynamic_test_helper.py"']
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/utils/libcxx/test/config.py:164: note: Using warnings: ['-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER', '-Wall', '-Wextra', '-Werror', '-Wuser-defined-warnings', '-Wshadow', '-Wno-unused-command-line-argument', '-Wno-attributes', '-Wno-pessimizing-move', '-Wno-c++11-extensions', '-Wno-user-defined-literals', '-Wno-noexcept-type', '-Wno-aligned-allocation-unavailable', '-Wsign-compare', '-Wunused-variable', '-Wunused-parameter', '-Wunreachable-code', '-Wno-conversion', '-Wno-unused-local-typedef', '-Wno-#warnings']
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/utils/libcxx/test/config.py:165: note: Using link flags: ['-L/root/Downloads/LLVM/build.llvm/./lib', '-Wl,-rpath,/root/Downloads/LLVM/build.llvm/./lib', '-nodefaultlibs', '-lc++experimental', '-lc++', '-lm', '-lgcc_s', '-lgcc', '-lpthread', '-lc', '-lgcc_s', '-lgcc']
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/utils/libcxx/test/config.py:168: note: Using available_features: ['libc++', 'verify-support', 'clang-5', 'glibc-2.13', 'glibc-2', 'modules-support', 'linux', 'diagnose-if-support', 'long_tests', 'c++filesystem', 'fdelayed-template-parsing', 'glibc', 'c++2a', 'thread-safety', 'c++experimental', 'clang', 'gentoo-base-system-2.1', 'libatomic', 'fsized-deallocation', 'fcoroutines-ts', 'clang-5.0', 'gentoo-base-system', '-faligned-allocation']
    llvm-lit: /root/Downloads/LLVM/llvm_src/projects/libcxx/utils/libcxx/test/config.py:173: note: Adding environment variables: {'LIBCXX_FILESYSTEM_DYNAMIC_TEST_ROOT': '/home/nao/Downloads/LLVM/build.llvm/projects/libcxx/test/filesystem/Output/dynamic_env'}
    FAIL: libc++ :: libcxx/containers/sequences/vector/asan_throw.pass.cpp (49 of 5872)
    ******************** TEST 'libc++ :: libcxx/containers/sequences/vector/asan_throw.pass.cpp' FAILED ********************
    Compiled With: ['/usr/local/bin/clang++', '-o', '/home/nao/Downloads/LLVM/build.llvm/projects/libcxx/test/libcxx/containers/sequences/vector/Output/asan_throw.pass.cpp.o', '-x', 'c++', '/home/nao/Downloads/LLVM/llvm_src/projects/libcxx/test/libcxx/containers/sequences/vector/asan_throw.pass.cpp', '-c', '-v', '-D_LIBCPP_DISABLE_AVAILABILITY', '-ftemplate-depth=270', '-Werror=thread-safety', '-std=c++2a', '-include', '/root/Downloads/LLVM/llvm_src/projects/libcxx/test/support/nasty_macros.hpp', '-nostdinc++', '-I/root/Downloads/LLVM/llvm_src/projects/libcxx/include', '-I/root/Downloads/LLVM/build.llvm/projects/libcxx/include/c++build', '-D__STDC_FORMAT_MACROS', '-D__STDC_LIMIT_MACROS', '-D__STDC_CONSTANT_MACROS', '-I/root/Downloads/LLVM/llvm_src/projects/libcxx/test/support', '-DLIBCXX_FILESYSTEM_STATIC_TEST_ROOT="/home/nao/Downloads/LLVM/llvm_src/projects/libcxx/test/std/experimental/filesystem/Inputs/static_test_env"', '-DLIBCXX_FILESYSTEM_DYNAMIC_TEST_ROOT="/home/nao/Downloads/LLVM/build.llvm/projects/libcxx/test/filesystem/Output/dynamic_env"', '-DLIBCXX_FILESYSTEM_DYNAMIC_TEST_HELPER="/usr/bin/python2.7 /root/Downloads/LLVM/llvm_src/projects/libcxx/test/support/filesystem_dynamic_test_helper.py"', '-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER', '-Wall', '-Wextra', '-Werror', '-Wuser-defined-warnings', '-Wshadow', '-Wno-unused-command-line-argument', '-Wno-attributes', '-Wno-pessimizing-move', '-Wno-c++11-extensions', '-Wno-user-defined-literals', '-Wno-noexcept-type', '-Wno-aligned-allocation-unavailable', '-Wsign-compare', '-Wunused-variable', '-Wunused-parameter', '-Wunreachable-code', '-Wno-conversion', '-Wno-unused-local-typedef', '-Wno-#warnings', '-c', '&&', '/usr/local/bin/clang++', '-o', '/home/nao/Downloads/LLVM/build.llvm/projects/libcxx/test/libcxx/containers/sequences/vector/Output/asan_throw.pass.cpp.exe', '/home/nao/Downloads/LLVM/build.llvm/projects/libcxx/test/libcxx/containers/sequences/vector/Output/asan_throw.pass.cpp.o', '-v', '-D_LIBCPP_DISABLE_AVAILABILITY', '-ftemplate-depth=270', '-L/root/Downloads/LLVM/build.llvm/./lib', '-Wl,-rpath,/root/Downloads/LLVM/build.llvm/./lib', '-nodefaultlibs', '-lc++experimental', '-lc++', '-lm', '-lgcc_s', '-lgcc', '-lpthread', '-lc', '-lgcc_s', '-lgcc']
    Command: ['/home/nao/Downloads/LLVM/build.llvm/projects/libcxx/test/libcxx/containers/sequences/vector/Output/asan_throw.pass.cpp.exe']
    Exit Code: -11
    
    Compiled test failed unexpectedly!
    ********************
    FAIL: libc++ :: libcxx/debug/containers/db_associative_container_tests.pass.cpp (73 of 5872)
    ******************** TEST 'libc++ :: libcxx/debug/containers/db_associative_container_tests.pass.cpp' FAILED ********************

Any help overcoming these problems are most welcome!

I have GCC/G++ 4.8.5 built and installed in `/usr/local/bin` and it is the default GNU compiler.  However, if I don't specify which compiler to use when building LLVM, my GCC 4,5,3 is invoked (presumably because it's found first).  When I run `g++ -E -x c++ - -v < /dev/null` (notice that the 4.8.5 version is invoked), I get the following information:  

    Using built-in specs.
    COLLECT_GCC=g++
    Target: i686-pc-linux-gnu
    Configured with: ../gcc-4.8.5/configure --enable-languages=c,c++,objc,obj-c++ --enable-threads=posix
    Thread model: posix
    gcc version 4.8.5 (GCC)
    COLLECT_GCC_OPTIONS='-E' '-v' '-shared-libgcc' '-mtune=generic' '-march=pentiumpro'
     /home/persistent/local/bin/../libexec/gcc/i686-pc-linux-gnu/4.8.5/cc1plus -E -quiet -v -iprefix /home/persistent/local/bin/../lib/gcc/i686-pc-linux-gnu/4.8.5/ -D_GNU_SOURCE - -mtune=generic -march=pentiumpro
    ignoring nonexistent directory "/home/persistent/local/bin/../lib/gcc/i686-pc-linux-gnu/4.8.5/../../../../i686-pc-linux-gnu/include"
    ignoring duplicate directory "/home/persistent/local/bin/../lib/gcc/../../lib/gcc/i686-pc-linux-gnu/4.8.5/../../../../include/c++/4.8.5"
    ignoring duplicate directory "/home/persistent/local/bin/../lib/gcc/../../lib/gcc/i686-pc-linux-gnu/4.8.5/../../../../include/c++/4.8.5/i686-pc-linux-gnu"
    ignoring duplicate directory "/home/persistent/local/bin/../lib/gcc/../../lib/gcc/i686-pc-linux-gnu/4.8.5/../../../../include/c++/4.8.5/backward"
    ignoring duplicate directory "/home/persistent/local/bin/../lib/gcc/../../lib/gcc/i686-pc-linux-gnu/4.8.5/include"
    ignoring duplicate directory "/home/persistent/local/bin/../lib/gcc/../../lib/gcc/i686-pc-linux-gnu/4.8.5/include-fixed"
    ignoring nonexistent directory "/home/persistent/local/bin/../lib/gcc/../../lib/gcc/i686-pc-linux-gnu/4.8.5/../../../../i686-pc-linux-gnu/include"
    #include "..." search starts here:
    #include <...> search starts here:
     /home/persistent/local/bin/../lib/gcc/i686-pc-linux-gnu/4.8.5/../../../../include/c++/4.8.5
     /home/persistent/local/bin/../lib/gcc/i686-pc-linux-gnu/4.8.5/../../../../include/c++/4.8.5/i686-pc-linux-gnu
     /home/persistent/local/bin/../lib/gcc/i686-pc-linux-gnu/4.8.5/../../../../include/c++/4.8.5/backward
     /home/persistent/local/bin/../lib/gcc/i686-pc-linux-gnu/4.8.5/include
     /home/persistent/local/bin/../lib/gcc/i686-pc-linux-gnu/4.8.5/include-fixed
     /usr/local/include
     /usr/include
    End of search list.
    # 1 "<stdin>"
    # 1 "<built-in>"
    # 1 "<command-line>"
    # 1 "<stdin>"
    COMPILER_PATH=/home/persistent/local/bin/../libexec/gcc/i686-pc-linux-gnu/4.8.5/:/home/persistent/local/bin/../libexec/gcc/
    LIBRARY_PATH=/home/persistent/local/bin/../lib/gcc/i686-pc-linux-gnu/4.8.5/:/home/persistent/local/bin/../lib/gcc/:/home/persistent/local/bin/../lib/gcc/i686-pc-linux-gnu/4.8.5/../../../:/lib/:/usr/lib/
    COLLECT_GCC_OPTIONS='-E' '-v' '-shared-libgcc' '-mtune=generic' '-march=pentiumpro'

**Comment by Napoleon-BlownApart** [comment]
problem solved by setting `--gcc-toolchain=/usr/local/` to point to my GCC 4.8.5 located in `/usr/local` (thus overriding the default GCC 4.5.3 that is located in `/usr`.  
`LIBCXX_BUILD_32_BITS=ON` was not required.

**Comment by vans8800** [comment]
I encountered the same error information as follows:
```
-- Performing Test LLVM_NO_OLD_LIBSTDCXX
-- Performing Test LLVM_NO_OLD_LIBSTDCXX - Failed
CMake Error at cmake/modules/CheckCompilerVersion.cmake:38 (message):
  Host Clang must be able to find libstdc++4.8 or newer!
Call Stack (most recent call first):
  cmake/config-ix.cmake:13 (include)
  CMakeLists.txt:587 (include)


-- Configuring incomplete, errors occurred!
See also "/root/rpmbuild/BUILD/llvm-clang-8.0.0/build/CMakeFiles/CMakeOutput.log".
See also "/root/rpmbuild/BUILD/llvm-clang-8.0.0/build/CMakeFiles/CMakeError.log".
error: Bad exit status from /var/tmp/rpm-tmp.hk3CXg (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.hk3CXg (%build)
```
Then my gcc info and libstdc++ info as follows:
```
[root@localhost SPECS]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/mips64el-redhat-linux/4.9.3/lto-wrapper
Target: mips64el-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-arch=loongson3a --enable-languages=c,c++,objc,obj-c++,fortran,go,lto --enable-plugin --disable-libgcj --with-isl=/root/rpmbuild/BUILD/gcc-4.9.3/obj-mips64el-redhat-linux/isl-install --with-cloog=/root/rpmbuild/BUILD/gcc-4.9.3/obj-mips64el-redhat-linux/cloog-install --enable-gnu-indirect-function --with-long-double-128 --build=mips64el-redhat-linux
Thread model: posix
gcc version 4.9.3 20150626 (Red Hat 4.9.3-11) (GCC)
[root@localhost SPECS]# rpm -qa  | grep gcc
gcc-base-debuginfo-4.9.3-11.fc21.loongson.11.mips64el
gcc-gfortran-4.9.3-11.fc21.loongson.11.mips64el
cross-gcc-common-4.9.1-2.fc21.loongson.2.noarch
gcc-objc++-4.9.3-11.fc21.loongson.11.mips64el
gcc-mips64-linux-gnu-4.9.1-2.fc21.loongson.2.mips64el
gcc-objc-4.9.3-11.fc21.loongson.11.mips64el
libgcc-4.9.3-11.fc21.loongson.11.mips64el
devtoolset-7-gcc-7.3.1-5.13.fc21.loongson.3.mips64el
gcc-debuginfo-4.9.3-11.fc21.loongson.11.mips64el
gcc-plugin-devel-4.9.3-11.fc21.loongson.11.mips64el
gcc-c++-mips64-linux-gnu-4.9.1-2.fc21.loongson.2.mips64el
devtoolset-7-gcc-c++-7.3.1-5.13.fc21.loongson.3.mips64el
gcc-c++-4.9.3-11.fc21.loongson.11.mips64el
gcc-go-4.9.3-11.fc21.loongson.11.mips64el
gcc-4.9.3-11.fc21.loongson.11.mips64el
[root@localhost SPECS]# rpm -qa  | grep libstdc++
libstdc++-4.9.3-11.fc21.loongson.11.mips64el
libstdc++-static-4.9.3-11.fc21.loongson.11.mips64el
devtoolset-7-libstdc++-devel-7.3.1-5.13.fc21.loongson.3.mips64el
libstdc++-devel-4.9.3-11.fc21.loongson.11.mips64el
libstdc++-docs-4.9.3-11.fc21.loongson.11.mips64el


```
Anybody Can give me some hints , about the adove problem?  Many Thanks, sincerely。
